"""
Auto-generated API smoke tests configuration
Generated by tools/generate_api_tests.py

Phase 1 Enhancement: Real test data fixtures for path parameter resolution
Phase 2 Enhancement: SAVEPOINT isolation — all test data rolled back per test
"""

import pytest
import uuid
from fastapi.testclient import TestClient
from sqlalchemy import event
from sqlalchemy.orm import Session, sessionmaker
from datetime import date, datetime, timedelta, timezone
from typing import Dict, Optional

from app.main import app
from app.database import engine, get_db
from app.models.user import User, UserRole
from app.models.semester import Semester
from app.models.campus import Campus
from app.models.location import Location
from app.core.security import get_password_hash


@pytest.fixture(scope="session", autouse=True)
def _seed_tournament_types_once():
    """Seed tournament_types table from JSON configs if empty (idempotent, session-scoped)."""
    import json
    import os
    from app.models.tournament_type import TournamentType

    db = next(get_db())
    try:
        if db.query(TournamentType).count() == 0:
            base_path = os.path.join(
                os.path.dirname(__file__), "..", "..", "..", "app", "tournament_types"
            )
            for filename in ["league.json", "knockout.json", "group_knockout.json", "swiss.json"]:
                config_path = os.path.join(base_path, filename)
                if not os.path.exists(config_path):
                    continue
                with open(config_path) as f:
                    config = json.load(f)
                db.add(TournamentType(
                    code=config["code"],
                    display_name=config["display_name"],
                    description=config.get("description"),
                    format=config.get("format", "HEAD_TO_HEAD"),
                    min_players=config.get("min_players", 4),
                    max_players=config.get("max_players"),
                    requires_power_of_two=config.get("requires_power_of_two", False),
                    session_duration_minutes=config.get("session_duration_minutes", 90),
                    break_between_sessions_minutes=config.get("break_between_sessions_minutes", 15),
                    config=config,
                ))
            db.commit()
    finally:
        db.close()


# ── Domain → API prefix map ───────────────────────────────────────────────────
# Auto-generated smoke tests use paths relative to the router prefix, e.g.
# GET "/" in test_users_smoke.py should be GET "/api/v1/users/".
# The PrefixedClient wrapper prepends the correct prefix per test module.
#
# Mapping key = stem between "test_" and "_smoke" in the filename.
# Values sourced from app router include_router() calls.
_DOMAIN_PREFIX_MAP: dict[str, str] = {
    # ── Standard API domains ──────────────────────────────────────────────
    "_semesters_main":       "/api/v1/semesters",
    "adaptive_learning":     "/api/v1/adaptive-learning",
    "admin":                 "/api/v1/admin",
    "analytics":             "/api/v1/analytics",
    "attendance":            "/api/v1/attendance",
    "audit":                 "/api/v1/audit",
    "auth":                  "/api/v1/auth",
    "bookings":              "/api/v1/bookings",
    "campuses":              "/api/v1/admin",          # routes: /api/v1/admin/campuses/...
    "certificates":          "/api/v1/certificates",
    "coach":                 "/api/v1/coach",
    "competency":            "/api/v1/competency",
    "coupons":               "/api/v1/coupons",
    "curriculum":            "/api/v1/curriculum",
    "curriculum_adaptive":   "/api/v1/curriculum-adaptive",
    "debug":                 "/api/v1/debug",
    "enrollments":           "/api/v1/enrollments",
    "feedback":              "/api/v1/feedback",
    "game_presets":          "/api/v1/game-presets",
    "gamification":          "/api/v1/gamification",
    "gancuju":               "/api/v1/gancuju",
    "gancuju_routes":        "/api/v1/gancuju",
    "groups":                "/api/v1/groups",
    "health":                "/api/v1/health",
    "instructor":            "/api/v1/instructor-management",
    "instructor_analytics":  "/api/v1/users",              # GET /users/instructor/students{/*}
    "instructor_assignments":"/api/v1/instructor-assignments",
    "instructor_availability":"/api/v1/instructor-availability",
    "instructor_dashboard":  "/api/v1/instructor-management",
    "instructor_management": "/api/v1/instructor-management",
    "internship":            "/api/v1/internship",
    "internship_routes":     "/api/v1/internship",
    "invitation_codes":      "/api/v1/invitation-codes",
    "invoices":              "/api/v1/invoices",
    "lfa_coach_routes":      "/api/v1/coach",
    "lfa_player":            "/api/v1/lfa-player",
    "lfa_player_routes":     "/api/v1/lfa-player",
    "license_renewal":       "/api/v1/license-renewal",
    "licenses":              "/api/v1/licenses",
    "locations":             "/api/v1/admin/locations",
    "messages":              "/api/v1/messages",
    "assignment_requests":   "/api/v1/instructor-assignments",  # CRUD for assignment requests
    "license_skills":        "/api/v1/licenses",               # GET/PUT football skills
    "milestones":            "/api/v1/projects",               # POST /projects/{id}/milestones/{id}/...
    "masters":               "/api/v1/instructor-management",  # /masters/* sub-routes
    "positions":             "/api/v1/instructor-management",  # CRUD for positions
    "project_quizzes":       "/api/v1/projects",               # POST/GET/DELETE project quizzes
    "quiz_attempts":         "/api/v1/quizzes",                # POST /quizzes/start, POST /quizzes/submit
    "motivation":            "/api/v1/licenses",       # /api/v1/licenses/motivation-assessment
    "notifications":         "/api/v1/notifications",
    "onboarding":            "",                       # Streamlit UI routes (no /api/v1/)
    "parallel_specializations": "/api/v1/parallel-specializations",
    "payment_verification":  "/api/v1/payment-verification",
    "periods":               "/api/v1/admin/periods",
    "profile":               "",                       # Streamlit UI route (/profile)
    "progression":           "/api/v1/progression",
    "projects":              "/api/v1/projects",
    "public_profile":        "/api/v1/users",          # GET /users/{id}/profile/{type}
    "quiz":                  "/api/v1/quizzes",
    "reports":               "/api/v1/reports",
    "sandbox":               "/api/v1/sandbox",
    "semester_enrollments":  "/api/v1/semester-enrollments",
    "semester_generator":    "/api/v1/semesters",
    "semesters":             "/api/v1/semesters",
    "session_groups":        "/api/v1/session-groups",
    "sessions":              "/api/v1/sessions",
    "spec_info":             "/api/v1/spec-info",
    "specialization":        "/api/v1/specializations",
    "specializations":       "/api/v1/specializations",
    "student_features":      "",                       # Streamlit UI routes (/about-specializations etc.)
    "students":              "/api/v1/students",
    "system_events":         "/api/v1/system-events",
    "tournament_types":      "/api/v1/tournament-types",
    "tournaments":           "/api/v1/tournaments",
    "tracks":                "/api/v1/tracks",
    "users":                 "/api/v1/users",
    # ── Catch-all dashboard (Streamlit UI) ────────────────────────────────
    "dashboard":             "",                       # Streamlit UI route (/dashboard)
}


class _PrefixedClient:
    """
    Thin wrapper around TestClient that prepends a domain prefix to every
    HTTP method call.  Smoke tests use paths relative to their domain router
    (e.g. GET "/" instead of GET "/api/v1/users/").  This wrapper fixes that
    transparently without touching the auto-generated test files.
    """

    def __init__(self, base_client: TestClient, prefix: str) -> None:
        self._client = base_client
        self._prefix = prefix

    def _url(self, path: str) -> str:
        # If path is already absolute (starts with /api/ or has no prefix to add),
        # pass it through unchanged — avoids double-prefixing for enhanced test
        # files that already include the full route path.
        if not self._prefix or path.startswith("/api/"):
            return path
        return self._prefix + path

    def get(self, url, **kwargs):
        return self._client.get(self._url(url), **kwargs)

    def post(self, url, **kwargs):
        return self._client.post(self._url(url), **kwargs)

    def put(self, url, **kwargs):
        return self._client.put(self._url(url), **kwargs)

    def patch(self, url, **kwargs):
        return self._client.patch(self._url(url), **kwargs)

    def delete(self, url, **kwargs):
        return self._client.delete(self._url(url), **kwargs)

    # Expose status_code / headers / json for any test that accesses them
    # directly on the client object (rare but safe to proxy).
    def __getattr__(self, name):
        return getattr(self._client, name)


# ── SAVEPOINT isolation ────────────────────────────────────────────────────────
#
# Every test function gets a fresh PostgreSQL SAVEPOINT.  All DB writes
# (both in fixtures and inside endpoint handlers) are rolled back at teardown.
# This eliminates the 100+ accumulated smoke-test users/tournaments per CI run.


@pytest.fixture(scope="function")
def postgres_db():
    """
    PostgreSQL session with transactional rollback via SAVEPOINT.

    All writes — fixture setup AND endpoint handler DB calls — live inside a
    nested transaction.  The outer transaction is rolled back at teardown so
    nothing persists to the real database.
    """
    connection = engine.connect()
    transaction = connection.begin()

    TestSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=connection)
    session = TestSessionLocal()

    connection.begin_nested()

    @event.listens_for(session, "after_transaction_end")
    def restart_savepoint(session, txn):
        if txn.nested and not txn._parent.nested:
            session.begin_nested()

    try:
        yield session
    finally:
        session.close()
        if transaction.is_active:
            transaction.rollback()
        connection.close()


@pytest.fixture(scope="function")
def test_db(postgres_db: Session):
    """Transactional test session (alias for postgres_db)."""
    return postgres_db


@pytest.fixture(scope="function")
def api_client(request, test_db: Session):
    """
    FastAPI TestClient with per-domain path prefix and SAVEPOINT DB isolation.

    get_db is overridden to yield the same SAVEPOINT session used by fixtures,
    so endpoint handler DB operations participate in the per-test rollback.
    """
    import re
    module_stem = request.module.__name__.split(".")[-1]   # "test_users_smoke"
    match = re.search(r"^test_(.+?)_smoke$", module_stem)
    domain_key = match.group(1) if match else ""
    prefix = _DOMAIN_PREFIX_MAP.get(domain_key, "/api/v1")

    def override_get_db():
        try:
            yield test_db
        finally:
            pass

    app.dependency_overrides[get_db] = override_get_db
    base_client = TestClient(app, follow_redirects=False)
    try:
        yield _PrefixedClient(base_client, prefix)
    finally:
        app.dependency_overrides.pop(get_db, None)


# ── User fixtures (function-scoped, UUID emails, always fresh) ─────────────────


@pytest.fixture(scope="function")
def _admin_user(test_db: Session) -> User:
    """Fresh admin user per test — rolled back at teardown."""
    unique_suffix = uuid.uuid4().hex[:8]
    user = User(
        name="Smoke Test Admin",
        email=f"smoke.admin.{unique_suffix}@example.com",
        password_hash=get_password_hash("admin123"),
        role=UserRole.ADMIN,
        is_active=True,
    )
    test_db.add(user)
    test_db.commit()
    test_db.refresh(user)
    return user


@pytest.fixture(scope="function")
def _student_user(test_db: Session) -> User:
    """Fresh student user per test — rolled back at teardown."""
    unique_suffix = uuid.uuid4().hex[:8]
    user = User(
        name="Smoke Test Student",
        email=f"smoke.student.{unique_suffix}@example.com",
        password_hash=get_password_hash("student123"),
        role=UserRole.STUDENT,
        is_active=True,
        date_of_birth=date(2000, 1, 1),
        credit_balance=5000,
    )
    test_db.add(user)
    test_db.commit()
    test_db.refresh(user)
    return user


@pytest.fixture(scope="function")
def _instructor_user(test_db: Session) -> User:
    """Fresh instructor user per test — rolled back at teardown."""
    unique_suffix = uuid.uuid4().hex[:8]
    user = User(
        name="Smoke Test Instructor",
        email=f"smoke.instructor.{unique_suffix}@example.com",
        password_hash=get_password_hash("instructor123"),
        role=UserRole.INSTRUCTOR,
        is_active=True,
    )
    test_db.add(user)
    test_db.commit()
    test_db.refresh(user)
    return user


@pytest.fixture(scope="function")
def admin_token(_admin_user: User) -> str:
    """Admin authentication token for the per-test admin user."""
    from app.core.auth import create_access_token
    return create_access_token(data={"sub": _admin_user.email}, expires_delta=timedelta(hours=1))


@pytest.fixture(scope="function")
def student_token(_student_user: User) -> str:
    """Student authentication token for the per-test student user."""
    from app.core.auth import create_access_token
    return create_access_token(data={"sub": _student_user.email}, expires_delta=timedelta(hours=1))


@pytest.fixture(scope="function")
def instructor_token(_instructor_user: User) -> str:
    """Instructor authentication token for the per-test instructor user."""
    from app.core.auth import create_access_token
    return create_access_token(data={"sub": _instructor_user.email}, expires_delta=timedelta(hours=1))


@pytest.fixture(scope="function")
def test_campus_id(test_db: Session) -> int:
    """
    Campus ID for tournament session generation.

    Prefers an existing active campus (seeded by bootstrap) to avoid
    redundant Location/Campus rows.  Falls back to creating one within
    the SAVEPOINT (rolled back at teardown).
    """
    existing_campus = test_db.query(Campus).filter(Campus.is_active.is_(True)).first()
    if existing_campus:
        return existing_campus.id

    location = test_db.query(Location).filter(Location.is_active.is_(True)).first()
    if not location:
        location = Location(
            name="Smoke Test Location",
            city="Budapest",
            country="Hungary",
            is_active=True,
        )
        test_db.add(location)
        test_db.commit()
        test_db.refresh(location)

    campus = Campus(
        name="Smoke Test Campus",
        location_id=location.id,
        address="Test Address 123",
        is_active=True,
    )
    test_db.add(campus)
    test_db.commit()
    test_db.refresh(campus)
    return campus.id


@pytest.fixture(scope="function")
def test_tournament(test_db: Session, test_campus_id: int, _student_user: User) -> Dict:
    """
    P2.1: Minimál Lifecycle Graph — State-driven test architecture.

    Creates a complete tournament with minimal viable state:
    - Tournament entity (Semester)
    - Campus schedule config
    - Reward config
    - 4 Students with LFA_FOOTBALL_PLAYER licenses (knockout min_players=4)
    - 4 Enrollments (APPROVED, is_active=True)
    - 1 Session (tournament_round=1)

    All data is rolled back at teardown via SAVEPOINT isolation.

    Returns:
        {
            "tournament_id": int,
            "semester_id": int,
            "code": str,
            "name": str,
            "session_ids": List[int],
            "enrolled_student_ids": List[int],
            "has_reward_config": bool,
            "has_campus_schedule": bool,
            "has_sessions": bool,
            "has_enrollments": bool
        }
    """
    from app.models.campus_schedule_config import CampusScheduleConfig
    from app.models.tournament_reward_config import TournamentRewardConfig
    from app.models.license import UserLicense
    from app.models.semester_enrollment import SemesterEnrollment, EnrollmentStatus
    from app.models.session import Session as SessionModel

    unique_suffix = uuid.uuid4().hex[:8].upper()

    tournament = Semester(
        code=f"SMOKE_TEST_{unique_suffix}",
        name=f"Smoke Test Tournament {unique_suffix}",
        start_date=datetime.now(timezone.utc).date(),
        end_date=(datetime.now(timezone.utc) + timedelta(days=30)).date(),
        tournament_status="IN_PROGRESS",
        enrollment_cost=0,
        age_group="PRO",
        campus_id=test_campus_id,
    )
    test_db.add(tournament)
    test_db.commit()
    test_db.refresh(tournament)

    campus_schedule = CampusScheduleConfig(
        tournament_id=tournament.id,
        campus_id=test_campus_id,
        match_duration_minutes=90,
        break_duration_minutes=15,
        parallel_fields=1,
        is_active=True,
    )
    test_db.add(campus_schedule)

    reward_config = TournamentRewardConfig(
        semester_id=tournament.id,
        reward_policy_name="smoke_test_policy",
    )
    test_db.add(reward_config)
    test_db.commit()

    # 4 students: student1 = _student_user; students 2-4 created fresh
    students = [_student_user]
    for i in range(2, 5):
        suffix_i = uuid.uuid4().hex[:8]
        s = User(
            name=f"Smoke Test Student {i}",
            email=f"smoke.student{i}.{suffix_i}@example.com",
            password_hash=get_password_hash("student123"),
            role=UserRole.STUDENT,
            is_active=True,
            credit_balance=1000,
        )
        test_db.add(s)
        test_db.commit()
        test_db.refresh(s)
        students.append(s)

    enrolled_student_ids = []
    for student in students:
        user_license = test_db.query(UserLicense).filter(
            UserLicense.user_id == student.id,
            UserLicense.specialization_type == "LFA_FOOTBALL_PLAYER",
        ).first()

        if not user_license:
            user_license = UserLicense(
                user_id=student.id,
                specialization_type="LFA_FOOTBALL_PLAYER",
                current_level=1,
                max_achieved_level=1,
                started_at=datetime.now(timezone.utc),
                is_active=True,
            )
            test_db.add(user_license)
            test_db.commit()
            test_db.refresh(user_license)

        enrollment = SemesterEnrollment(
            user_id=student.id,
            semester_id=tournament.id,
            user_license_id=user_license.id,
            request_status=EnrollmentStatus.APPROVED,
            is_active=True,
            requested_at=datetime.now(timezone.utc),
            approved_at=datetime.now(timezone.utc),
            enrolled_at=datetime.now(timezone.utc),
            age_category="PRO",
        )
        test_db.add(enrollment)
        enrolled_student_ids.append(student.id)

    test_db.commit()

    session_start = datetime.now(timezone.utc) + timedelta(days=1)
    session_end = session_start + timedelta(hours=2)

    session = SessionModel(
        title="Smoke Test Session - Round 1",
        description="Minimal lifecycle graph session",
        date_start=session_start,
        date_end=session_end,
        semester_id=tournament.id,
        campus_id=test_campus_id,
        tournament_round=1,
        tournament_match_number=1,
        session_status="scheduled",
        capacity=16,
    )
    test_db.add(session)
    test_db.commit()
    test_db.refresh(session)

    return {
        "tournament_id": tournament.id,
        "semester_id": tournament.id,
        "code": tournament.code,
        "name": tournament.name,
        "session_ids": [session.id],
        "enrolled_student_ids": enrolled_student_ids,
        "campus_id": test_campus_id,
        "has_reward_config": True,
        "has_campus_schedule": True,
        "has_sessions": True,
        "has_enrollments": True,
    }


@pytest.fixture(scope="function")
def test_student_id(_student_user: User) -> int:
    """Student user ID for badge/user endpoints."""
    return _student_user.id


@pytest.fixture(scope="function")
def test_instructor_id(_instructor_user: User) -> int:
    """Instructor user ID for instructor endpoints."""
    return _instructor_user.id


@pytest.fixture(scope="module")
def payload_factory():
    """
    Phase 1: Payload factory for generating schema-compliant request payloads.

    Eliminates 422 validation errors by generating minimally valid payloads
    based on OpenAPI schema definitions.
    """
    from tests.integration.api_smoke.payload_factory import PayloadFactory

    # Get OpenAPI schema
    openapi_schema = app.openapi()

    # Create and return factory instance
    return PayloadFactory(openapi_schema)
