"""
Auto-generated API smoke tests configuration
Generated by tools/generate_api_tests.py

Phase 1 Enhancement: Real test data fixtures for path parameter resolution
"""

import pytest
import uuid
from fastapi.testclient import TestClient
from sqlalchemy.orm import Session
from datetime import date, datetime, timedelta, timezone
from typing import Dict, Optional

from app.main import app
from app.database import get_db
from app.models.user import User, UserRole
from app.models.semester import Semester
from app.models.campus import Campus
from app.models.location import Location
from app.core.security import get_password_hash


@pytest.fixture(scope="session", autouse=True)
def _seed_tournament_types_once():
    """Seed tournament_types table from JSON configs if empty (idempotent, session-scoped)."""
    import json
    import os
    from app.models.tournament_type import TournamentType

    db = next(get_db())
    try:
        if db.query(TournamentType).count() == 0:
            base_path = os.path.join(
                os.path.dirname(__file__), "..", "..", "..", "app", "tournament_types"
            )
            for filename in ["league.json", "knockout.json", "group_knockout.json", "swiss.json"]:
                config_path = os.path.join(base_path, filename)
                if not os.path.exists(config_path):
                    continue
                with open(config_path) as f:
                    config = json.load(f)
                db.add(TournamentType(
                    code=config["code"],
                    display_name=config["display_name"],
                    description=config.get("description"),
                    format=config.get("format", "HEAD_TO_HEAD"),
                    min_players=config.get("min_players", 4),
                    max_players=config.get("max_players"),
                    requires_power_of_two=config.get("requires_power_of_two", False),
                    session_duration_minutes=config.get("session_duration_minutes", 90),
                    break_between_sessions_minutes=config.get("break_between_sessions_minutes", 15),
                    config=config,
                ))
            db.commit()
    finally:
        db.close()


# ── Domain → API prefix map ───────────────────────────────────────────────────
# Auto-generated smoke tests use paths relative to the router prefix, e.g.
# GET "/" in test_users_smoke.py should be GET "/api/v1/users/".
# The PrefixedClient wrapper prepends the correct prefix per test module.
#
# Mapping key = stem between "test_" and "_smoke" in the filename.
# Values sourced from app router include_router() calls.
_DOMAIN_PREFIX_MAP: dict[str, str] = {
    # ── Standard API domains ──────────────────────────────────────────────
    "_semesters_main":       "/api/v1/semesters",
    "adaptive_learning":     "/api/v1/adaptive-learning",
    "admin":                 "/api/v1/admin",
    "analytics":             "/api/v1/analytics",
    "attendance":            "/api/v1/attendance",
    "audit":                 "/api/v1/audit",
    "auth":                  "/api/v1/auth",
    "bookings":              "/api/v1/bookings",
    "campuses":              "/api/v1/admin",          # routes: /api/v1/admin/campuses/...
    "certificates":          "/api/v1/certificates",
    "coach":                 "/api/v1/coach",
    "competency":            "/api/v1/competency",
    "coupons":               "/api/v1/coupons",
    "curriculum":            "/api/v1/curriculum",
    "curriculum_adaptive":   "/api/v1/curriculum-adaptive",
    "debug":                 "/api/v1/debug",
    "enrollments":           "/api/v1/enrollments",
    "feedback":              "/api/v1/feedback",
    "game_presets":          "/api/v1/game-presets",
    "gamification":          "/api/v1/gamification",
    "gancuju":               "/api/v1/gancuju",
    "gancuju_routes":        "/api/v1/gancuju",
    "groups":                "/api/v1/groups",
    "health":                "/api/v1/health",
    "instructor":            "/api/v1/instructor-management",
    "instructor_analytics":  "/api/v1/users",              # GET /users/instructor/students{/*}
    "instructor_assignments":"/api/v1/instructor-assignments",
    "instructor_availability":"/api/v1/instructor-availability",
    "instructor_dashboard":  "/api/v1/instructor-management",
    "instructor_management": "/api/v1/instructor-management",
    "internship":            "/api/v1/internship",
    "internship_routes":     "/api/v1/internship",
    "invitation_codes":      "/api/v1/invitation-codes",
    "invoices":              "/api/v1/invoices",
    "lfa_coach_routes":      "/api/v1/coach",
    "lfa_player":            "/api/v1/lfa-player",
    "lfa_player_routes":     "/api/v1/lfa-player",
    "license_renewal":       "/api/v1/license-renewal",
    "licenses":              "/api/v1/licenses",
    "locations":             "/api/v1/admin/locations",
    "messages":              "/api/v1/messages",
    "assignment_requests":   "/api/v1/instructor-assignments",  # CRUD for assignment requests
    "license_skills":        "/api/v1/licenses",               # GET/PUT football skills
    "milestones":            "/api/v1/projects",               # POST /projects/{id}/milestones/{id}/...
    "masters":               "/api/v1/instructor-management",  # /masters/* sub-routes
    "positions":             "/api/v1/instructor-management",  # CRUD for positions
    "project_quizzes":       "/api/v1/projects",               # POST/GET/DELETE project quizzes
    "quiz_attempts":         "/api/v1/quizzes",                # POST /quizzes/start, POST /quizzes/submit
    "motivation":            "/api/v1/licenses",       # /api/v1/licenses/motivation-assessment
    "notifications":         "/api/v1/notifications",
    "onboarding":            "",                       # Streamlit UI routes (no /api/v1/)
    "parallel_specializations": "/api/v1/parallel-specializations",
    "payment_verification":  "/api/v1/payment-verification",
    "periods":               "/api/v1/admin/periods",
    "profile":               "",                       # Streamlit UI route (/profile)
    "progression":           "/api/v1/progression",
    "projects":              "/api/v1/projects",
    "public_profile":        "/api/v1/users",          # GET /users/{id}/profile/{type}
    "quiz":                  "/api/v1/quizzes",
    "reports":               "/api/v1/reports",
    "sandbox":               "/api/v1/sandbox",
    "semester_enrollments":  "/api/v1/semester-enrollments",
    "semester_generator":    "/api/v1/semesters",
    "semesters":             "/api/v1/semesters",
    "session_groups":        "/api/v1/session-groups",
    "sessions":              "/api/v1/sessions",
    "spec_info":             "/api/v1/spec-info",
    "specialization":        "/api/v1/specializations",
    "specializations":       "/api/v1/specializations",
    "student_features":      "",                       # Streamlit UI routes (/about-specializations etc.)
    "students":              "/api/v1/students",
    "system_events":         "/api/v1/system-events",
    "tournament_types":      "/api/v1/tournament-types",
    "tournaments":           "/api/v1/tournaments",
    "tracks":                "/api/v1/tracks",
    "users":                 "/api/v1/users",
    # ── Catch-all dashboard (Streamlit UI) ────────────────────────────────
    "dashboard":             "",                       # Streamlit UI route (/dashboard)
}


class _PrefixedClient:
    """
    Thin wrapper around TestClient that prepends a domain prefix to every
    HTTP method call.  Smoke tests use paths relative to their domain router
    (e.g. GET "/" instead of GET "/api/v1/users/").  This wrapper fixes that
    transparently without touching the auto-generated test files.
    """

    def __init__(self, base_client: TestClient, prefix: str) -> None:
        self._client = base_client
        self._prefix = prefix

    def _url(self, path: str) -> str:
        # If path is already absolute (starts with /api/ or has no prefix to add),
        # pass it through unchanged — avoids double-prefixing for enhanced test
        # files that already include the full route path.
        if not self._prefix or path.startswith("/api/"):
            return path
        return self._prefix + path

    def get(self, url, **kwargs):
        return self._client.get(self._url(url), **kwargs)

    def post(self, url, **kwargs):
        return self._client.post(self._url(url), **kwargs)

    def put(self, url, **kwargs):
        return self._client.put(self._url(url), **kwargs)

    def patch(self, url, **kwargs):
        return self._client.patch(self._url(url), **kwargs)

    def delete(self, url, **kwargs):
        return self._client.delete(self._url(url), **kwargs)

    # Expose status_code / headers / json for any test that accesses them
    # directly on the client object (rare but safe to proxy).
    def __getattr__(self, name):
        return getattr(self._client, name)


@pytest.fixture(scope="module")
def api_client(request):
    """
    FastAPI TestClient with per-domain path prefix.

    Each smoke test module targets one API domain.  This fixture detects the
    domain from the test filename (e.g. test_users_smoke → "users") and wraps
    the raw TestClient in a _PrefixedClient that prepends /api/v1/<domain> to
    every request, so paths like GET "/" hit GET "/api/v1/users/" instead of
    the Streamlit root.
    """
    import re
    module_stem = request.module.__name__.split(".")[-1]   # "test_users_smoke"
    match = re.search(r"^test_(.+?)_smoke$", module_stem)
    domain_key = match.group(1) if match else ""
    prefix = _DOMAIN_PREFIX_MAP.get(domain_key, "/api/v1")

    base_client = TestClient(app, follow_redirects=False)
    return _PrefixedClient(base_client, prefix)


@pytest.fixture(scope="module")
def test_db():
    """Database session for test setup"""
    db = next(get_db())
    try:
        yield db
    finally:
        db.close()


@pytest.fixture(scope="module")
def admin_token(test_db: Session):
    """Admin user authentication token"""
    # Check if admin exists
    admin = test_db.query(User).filter(User.email == "smoke.admin@example.com").first()

    if not admin:
        admin = User(
            name="Smoke Test Admin",
            email="smoke.admin@example.com",
            password_hash=get_password_hash("admin123"),
            role=UserRole.ADMIN,
            is_active=True,
            date_of_birth=date(1980, 1, 1),
        )
        test_db.add(admin)
        test_db.commit()
        test_db.refresh(admin)

    # Generate token
    from app.core.auth import create_access_token
    token = create_access_token(data={"sub": admin.email}, expires_delta=timedelta(hours=1))
    return token


@pytest.fixture(scope="module")
def student_token(test_db: Session):
    """Student user authentication token"""
    student = test_db.query(User).filter(User.email == "smoke.student@example.com").first()

    if not student:
        student = User(
            name="Smoke Test Student",
            email="smoke.student@example.com",
            password_hash=get_password_hash("student123"),
            role=UserRole.STUDENT,
            is_active=True,
            date_of_birth=date(2000, 1, 1),
            credit_balance=5000
        )
        test_db.add(student)
        test_db.commit()
        test_db.refresh(student)
    else:
        # Ensure date_of_birth is set so enroll endpoint passes the dob check (line 143)
        if not student.date_of_birth:
            student.date_of_birth = date(2000, 1, 1)
            test_db.commit()

    from app.core.auth import create_access_token
    token = create_access_token(data={"sub": student.email}, expires_delta=timedelta(hours=1))
    return token


@pytest.fixture(scope="module")
def instructor_token(test_db: Session):
    """Instructor user authentication token"""
    instructor = test_db.query(User).filter(User.email == "smoke.instructor@example.com").first()

    if not instructor:
        instructor = User(
            name="Smoke Test Instructor",
            email="smoke.instructor@example.com",
            password_hash=get_password_hash("instructor123"),
            role=UserRole.INSTRUCTOR,
            is_active=True,
            date_of_birth=date(1990, 1, 1),
        )
        test_db.add(instructor)
        test_db.commit()
        test_db.refresh(instructor)

    from app.core.auth import create_access_token
    token = create_access_token(data={"sub": instructor.email}, expires_delta=timedelta(hours=1))
    return token


@pytest.fixture(scope="module")
def test_campus_id(test_db: Session) -> int:
    """
    Get or create a test campus for tournament session generation.

    Returns:
        Campus ID (int)
    """
    # Query existing campuses
    existing_campus = test_db.query(Campus).filter(Campus.is_active == True).first()

    if existing_campus:
        return existing_campus.id

    # Create test location if none exist
    location = test_db.query(Location).filter(Location.is_active == True).first()
    if not location:
        location = Location(
            name="Smoke Test Location",
            city="Budapest",
            country="Hungary",
            is_active=True
        )
        test_db.add(location)
        test_db.commit()
        test_db.refresh(location)

    # Create test campus
    campus = Campus(
        name="Smoke Test Campus",
        location_id=location.id,
        address="Test Address 123",
        is_active=True
    )
    test_db.add(campus)
    test_db.commit()
    test_db.refresh(campus)

    return campus.id


@pytest.fixture(scope="module")
def test_tournament(test_db: Session, test_campus_id: int, student_token: str) -> Dict:
    """
    P2.1: Minimál Lifecycle Graph - State-driven test architecture.

    Creates a complete tournament with minimal viable state:
    - Tournament entity (Semester)
    - Campus schedule config
    - Reward config
    - 4 Students with LFA_FOOTBALL_PLAYER licenses (knockout min_players=4)
    - 4 Enrollments (APPROVED, is_active=True)
    - 1 Session (tournament_round=1)

    Note: MatchStructure/MatchResult not included (tables don't exist in DB).

    Returns:
        {
            "tournament_id": int,
            "semester_id": int,
            "code": str,
            "name": str,
            "session_ids": List[int],
            "enrolled_student_ids": List[int],
            "has_reward_config": bool,
            "has_campus_schedule": bool,
            "has_sessions": bool,
            "has_enrollments": bool
        }
    """
    from app.models.campus_schedule_config import CampusScheduleConfig
    from app.models.tournament_reward_config import TournamentRewardConfig
    from app.models.license import UserLicense
    from app.models.semester_enrollment import SemesterEnrollment, EnrollmentStatus
    from app.models.session import Session as SessionModel

    # Use UUID suffix to prevent UniqueViolation when two CI jobs run within the same second
    unique_suffix = uuid.uuid4().hex[:8].upper()

    # Create tournament (game_preset_id moved to GameConfiguration in P3)
    tournament = Semester(
        code=f"SMOKE_TEST_{unique_suffix}",
        name=f"Smoke Test Tournament {unique_suffix}",
        start_date=datetime.now(timezone.utc).date(),
        end_date=(datetime.now(timezone.utc) + timedelta(days=30)).date(),
        tournament_status="IN_PROGRESS",
        enrollment_cost=0,
        age_group="PRO",
        campus_id=test_campus_id,
    )
    test_db.add(tournament)
    test_db.commit()
    test_db.refresh(tournament)

    # Add campus schedule config (minimal valid configuration)
    campus_schedule = CampusScheduleConfig(
        tournament_id=tournament.id,
        campus_id=test_campus_id,
        match_duration_minutes=90,
        break_duration_minutes=15,
        parallel_fields=1,
        is_active=True
    )
    test_db.add(campus_schedule)

    # Add reward config (minimal valid configuration)
    reward_config = TournamentRewardConfig(
        semester_id=tournament.id,
        reward_policy_name="smoke_test_policy"
    )
    test_db.add(reward_config)

    test_db.commit()

    # ── 4. Create 2 Students with PLAYER Licenses ──────────────────────
    # Get student 1 (created by student_token fixture)
    student1 = test_db.query(User).filter(User.email == "smoke.student@example.com").first()

    # Create student 2
    student2_email = f"smoke.student2.{unique_suffix}@example.com"
    student2 = test_db.query(User).filter(User.email == student2_email).first()
    if not student2:
        student2 = User(
            name="Smoke Test Student 2",
            email=student2_email,
            password_hash=get_password_hash("student123"),
            role=UserRole.STUDENT,
            is_active=True,
            date_of_birth=date(2000, 1, 1),
            credit_balance=1000
        )
        test_db.add(student2)
        test_db.commit()
        test_db.refresh(student2)

    # Create student 3
    student3_email = f"smoke.student3.{unique_suffix}@example.com"
    student3 = test_db.query(User).filter(User.email == student3_email).first()
    if not student3:
        student3 = User(
            name="Smoke Test Student 3",
            email=student3_email,
            password_hash=get_password_hash("student123"),
            role=UserRole.STUDENT,
            is_active=True,
            date_of_birth=date(2000, 1, 1),
            credit_balance=1000
        )
        test_db.add(student3)
        test_db.commit()
        test_db.refresh(student3)

    # Create student 4
    student4_email = f"smoke.student4.{unique_suffix}@example.com"
    student4 = test_db.query(User).filter(User.email == student4_email).first()
    if not student4:
        student4 = User(
            name="Smoke Test Student 4",
            email=student4_email,
            password_hash=get_password_hash("student123"),
            role=UserRole.STUDENT,
            is_active=True,
            date_of_birth=date(2000, 1, 1),
            credit_balance=1000
        )
        test_db.add(student4)
        test_db.commit()
        test_db.refresh(student4)

    # Create UserLicense + Enrollment for all 4 students
    # License type must be LFA_FOOTBALL_PLAYER — ops_scenario enrollment loop
    # filters by specialization_type == "LFA_FOOTBALL_PLAYER" (ops_scenario.py:1380)
    enrolled_student_ids = []
    for student in [student1, student2, student3, student4]:
        # Check if LFA_FOOTBALL_PLAYER license exists
        user_license = test_db.query(UserLicense).filter(
            UserLicense.user_id == student.id,
            UserLicense.specialization_type == "LFA_FOOTBALL_PLAYER"
        ).first()

        if not user_license:
            user_license = UserLicense(
                user_id=student.id,
                specialization_type="LFA_FOOTBALL_PLAYER",
                current_level=1,
                max_achieved_level=1,
                started_at=datetime.now(timezone.utc),
                is_active=True
            )
            test_db.add(user_license)
            test_db.commit()
            test_db.refresh(user_license)

        # ── 5. Create Enrollment (APPROVED, is_active=True) ────────────
        enrollment = SemesterEnrollment(
            user_id=student.id,
            semester_id=tournament.id,
            user_license_id=user_license.id,
            request_status=EnrollmentStatus.APPROVED,
            is_active=True,
            requested_at=datetime.now(timezone.utc),
            approved_at=datetime.now(timezone.utc),
            enrolled_at=datetime.now(timezone.utc),
            age_category="PRO"
        )
        test_db.add(enrollment)
        enrolled_student_ids.append(student.id)

    test_db.commit()

    # ── 6. Create 1 Session ─────────────────────────────────────────────
    session_start = datetime.now(timezone.utc) + timedelta(days=1)
    session_end = session_start + timedelta(hours=2)

    session = SessionModel(
        title=f"Smoke Test Session - Round 1",
        description="Minimal lifecycle graph session",
        date_start=session_start,
        date_end=session_end,
        semester_id=tournament.id,
        campus_id=test_campus_id,
        tournament_round=1,
        tournament_match_number=1,
        session_status="scheduled",
        capacity=16
    )
    test_db.add(session)
    test_db.commit()
    test_db.refresh(session)

    return {
        "tournament_id": tournament.id,
        "semester_id": tournament.id,
        "code": tournament.code,
        "name": tournament.name,
        "session_ids": [session.id],
        "enrolled_student_ids": enrolled_student_ids,
        "campus_id": test_campus_id,
        "has_reward_config": True,
        "has_campus_schedule": True,
        "has_sessions": True,
        "has_enrollments": True
    }


@pytest.fixture(scope="module")
def test_student_id(test_db: Session) -> int:
    """
    Get smoke test student user ID for badge/user endpoints.

    Returns:
        User ID (int)
    """
    student = test_db.query(User).filter(User.email == "smoke.student@example.com").first()
    assert student, "Smoke test student not found - ensure student_token fixture is called first"
    return student.id


@pytest.fixture(scope="module")
def test_instructor_id(test_db: Session, instructor_token: str) -> int:
    """
    Get smoke test instructor user ID for instructor endpoints.

    Explicit dependency: instructor_token fixture creates the instructor user.

    Returns:
        User ID (int)
    """
    instructor = test_db.query(User).filter(User.email == "smoke.instructor@example.com").first()
    assert instructor, "Smoke test instructor not found after instructor_token fixture"
    return instructor.id


@pytest.fixture(scope="module")
def payload_factory():
    """
    Phase 1: Payload factory for generating schema-compliant request payloads.

    Eliminates 422 validation errors by generating minimally valid payloads
    based on OpenAPI schema definitions.
    """
    from tests.integration.api_smoke.payload_factory import PayloadFactory

    # Get OpenAPI schema
    openapi_schema = app.openapi()

    # Create and return factory instance
    return PayloadFactory(openapi_schema)
