"""
Auto-generated smoke tests for sessions domain
Generated by tools/generate_api_tests.py

⚠️  DO NOT EDIT MANUALLY - Regenerate using:
    python tools/generate_api_tests.py --scan-api app/api --output tests/integration/api_smoke/
"""

import pytest
from fastapi.testclient import TestClient


class TestSessionsSmoke:
    """Smoke tests for sessions API endpoints"""


    # ── DELETE /{session_id} ────────────────────────────

    def test_delete_session_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: DELETE /{session_id}
        Source: app/api/api_v1/endpoints/sessions/crud.py:delete_session
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.delete("/{session_id}", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"DELETE /{session_id} failed: {response.status_code} "
            f"{response.text}"
        )

    def test_delete_session_auth_required(self, api_client: TestClient):
        """
        Auth validation: DELETE /{session_id} requires authentication
        """
        
        response = api_client.delete("/{session_id}")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"DELETE /{session_id} should require auth: {response.status_code}"
        )

    def test_list_sessions_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /
        Source: app/api/api_v1/endpoints/sessions/queries.py:list_sessions
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"GET / failed: {response.status_code} "
            f"{response.text}"
        )

    def test_list_sessions_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET / requires authentication
        """
        
        response = api_client.get("/")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"GET / should require auth: {response.status_code}"
        )

    def test_get_sessions_availability_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /availability
        Source: app/api/api_v1/endpoints/sessions/availability.py:get_sessions_availability
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/availability", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"GET /availability failed: {response.status_code} "
            f"{response.text}"
        )

    def test_get_sessions_availability_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /availability requires authentication
        """
        
        response = api_client.get("/availability")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"GET /availability should require auth: {response.status_code}"
        )

    def test_calendar_page_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /calendar
        Source: app/api/web_routes/sessions.py:calendar_page
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/calendar", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"GET /calendar failed: {response.status_code} "
            f"{response.text}"
        )

    def test_calendar_page_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /calendar requires authentication
        """
        
        response = api_client.get("/calendar")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"GET /calendar should require auth: {response.status_code}"
        )

    def test_get_calendar_events_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /calendar
        Source: app/api/api_v1/endpoints/sessions/queries.py:get_calendar_events
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/calendar", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"GET /calendar failed: {response.status_code} "
            f"{response.text}"
        )

    def test_get_calendar_events_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /calendar requires authentication
        """
        
        response = api_client.get("/calendar")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"GET /calendar should require auth: {response.status_code}"
        )

    def test_get_instructor_sessions_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /instructor/my
        Source: app/api/api_v1/endpoints/sessions/queries.py:get_instructor_sessions
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/instructor/my", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"GET /instructor/my failed: {response.status_code} "
            f"{response.text}"
        )

    def test_get_instructor_sessions_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /instructor/my requires authentication
        """
        
        response = api_client.get("/instructor/my")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"GET /instructor/my should require auth: {response.status_code}"
        )

    def test_get_session_recommendations_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /recommendations
        Source: app/api/api_v1/endpoints/sessions/queries.py:get_session_recommendations
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/recommendations", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"GET /recommendations failed: {response.status_code} "
            f"{response.text}"
        )

    def test_get_session_recommendations_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /recommendations requires authentication
        """
        
        response = api_client.get("/recommendations")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"GET /recommendations should require auth: {response.status_code}"
        )

    def test_sessions_page_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /sessions
        Source: app/api/web_routes/sessions.py:sessions_page
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/sessions", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"GET /sessions failed: {response.status_code} "
            f"{response.text}"
        )

    def test_sessions_page_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /sessions requires authentication
        """
        
        response = api_client.get("/sessions")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"GET /sessions should require auth: {response.status_code}"
        )

    def test_session_details_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /sessions/{session_id}
        Source: app/api/web_routes/sessions.py:session_details
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/sessions/{session_id}", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"GET /sessions/{session_id} failed: {response.status_code} "
            f"{response.text}"
        )

    def test_session_details_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /sessions/{session_id} requires authentication
        """
        
        response = api_client.get("/sessions/{session_id}")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"GET /sessions/{session_id} should require auth: {response.status_code}"
        )

    def test_get_session_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /{session_id}
        Source: app/api/api_v1/endpoints/sessions/crud.py:get_session
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/{session_id}", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"GET /{session_id} failed: {response.status_code} "
            f"{response.text}"
        )

    def test_get_session_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /{session_id} requires authentication
        """
        
        response = api_client.get("/{session_id}")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"GET /{session_id} should require auth: {response.status_code}"
        )

    def test_get_session_bookings_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /{session_id}/bookings
        Source: app/api/api_v1/endpoints/sessions/queries.py:get_session_bookings
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/{session_id}/bookings", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"GET /{session_id}/bookings failed: {response.status_code} "
            f"{response.text}"
        )

    def test_get_session_bookings_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /{session_id}/bookings requires authentication
        """
        
        response = api_client.get("/{session_id}/bookings")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"GET /{session_id}/bookings should require auth: {response.status_code}"
        )

    def test_get_game_results_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /{session_id}/results
        Source: app/api/api_v1/endpoints/sessions/results.py:get_game_results
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/{session_id}/results", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"GET /{session_id}/results failed: {response.status_code} "
            f"{response.text}"
        )

    def test_get_game_results_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /{session_id}/results requires authentication
        """
        
        response = api_client.get("/{session_id}/results")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"GET /{session_id}/results should require auth: {response.status_code}"
        )

    def test_update_session_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: PATCH /{session_id}
        Source: app/api/api_v1/endpoints/sessions/crud.py:update_session
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        payload = {}
        response = api_client.patch("/{session_id}", json=payload, headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"PATCH /{session_id} failed: {response.status_code} "
            f"{response.text}"
        )

    def test_update_session_auth_required(self, api_client: TestClient):
        """
        Auth validation: PATCH /{session_id} requires authentication
        """
        
        response = api_client.patch("/{session_id}", json={})
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"PATCH /{session_id} should require auth: {response.status_code}"
        )

    def test_update_session_input_validation(self, api_client: TestClient, admin_token: str):
        """
        Input validation: PATCH /{session_id} validates request data
        Tests: Invalid field types (title as int, capacity as string)
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        # Use dummy session_id for validation testing
        session_id = 99999

        # Invalid payload with wrong types
        invalid_payload = {
            "title": 12345,  # Should be string, not int
            "capacity": "not_a_number"  # Should be int, not string
        }
        response = api_client.patch(
            f"/api/v1/sessions/{session_id}",
            json=invalid_payload,
            headers=headers
        )

        # Should return 422 Unprocessable Entity for validation errors
        assert response.status_code in [400, 401, 403, 404, 422], (
            f"PATCH /{session_id} should validate input: {response.status_code}"
        )
        


    # ── PATCH /{session_id}/head-to-head-results ────────────────────────────

    def test_submit_head_to_head_match_result_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: PATCH /{session_id}/head-to-head-results
        Source: app/api/api_v1/endpoints/sessions/results.py:submit_head_to_head_match_result
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        payload = {}
        response = api_client.patch("/{session_id}/head-to-head-results", json=payload, headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"PATCH /{session_id}/head-to-head-results failed: {response.status_code} "
            f"{response.text}"
        )

    def test_submit_head_to_head_match_result_auth_required(self, api_client: TestClient):
        """
        Auth validation: PATCH /{session_id}/head-to-head-results requires authentication
        """
        
        response = api_client.patch("/{session_id}/head-to-head-results", json={})
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"PATCH /{session_id}/head-to-head-results should require auth: {response.status_code}"
        )

    def test_submit_head_to_head_match_result_input_validation(self, api_client: TestClient, admin_token: str):
        """
        Input validation: PATCH /{session_id}/head-to-head-results validates request data
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        # Invalid payload (empty or malformed)
        invalid_payload = {"invalid_field": "invalid_value"}
        response = api_client.patch(
            "/{session_id}/head-to-head-results",
            json=invalid_payload,
            headers=headers
        )

        # Should return 422 Unprocessable Entity for validation errors
        assert response.status_code in [400, 401, 403, 404, 422], (
            f"PATCH /{session_id}/head-to-head-results should validate input: {response.status_code}"
        )
        


    # ── PATCH /{session_id}/results ────────────────────────────

    def test_submit_game_results_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: PATCH /{session_id}/results
        Source: app/api/api_v1/endpoints/sessions/results.py:submit_game_results
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        payload = {}
        response = api_client.patch("/{session_id}/results", json=payload, headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"PATCH /{session_id}/results failed: {response.status_code} "
            f"{response.text}"
        )

    def test_submit_game_results_auth_required(self, api_client: TestClient):
        """
        Auth validation: PATCH /{session_id}/results requires authentication
        """
        
        response = api_client.patch("/{session_id}/results", json={})
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"PATCH /{session_id}/results should require auth: {response.status_code}"
        )

    def test_submit_game_results_input_validation(self, api_client: TestClient, admin_token: str):
        """
        Input validation: PATCH /{session_id}/results validates request data
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        # Invalid payload (empty or malformed)
        invalid_payload = {"invalid_field": "invalid_value"}
        response = api_client.patch(
            "/{session_id}/results",
            json=invalid_payload,
            headers=headers
        )

        # Should return 422 Unprocessable Entity for validation errors
        assert response.status_code in [400, 401, 403, 404, 422], (
            f"PATCH /{session_id}/results should validate input: {response.status_code}"
        )
        


    # ── POST / ────────────────────────────

    def test_create_session_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: POST /
        Source: app/api/api_v1/endpoints/sessions/crud.py:create_session
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        payload = {
            "title": "Smoke Test Session",
            "date_start": "2026-06-01T14:00:00",
            "date_end": "2026-06-01T16:00:00",
            "semester_id": 9999,
            "session_type": "on_site",
            "capacity": 20
        }
        response = api_client.post("/", json=payload, headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"POST / failed: {response.status_code} "
            f"{response.text}"
        )

    def test_create_session_auth_required(self, api_client: TestClient):
        """
        Auth validation: POST / requires authentication
        """
        
        response = api_client.post("/", json={})
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"POST / should require auth: {response.status_code}"
        )

    def test_create_session_input_validation(self, api_client: TestClient, admin_token: str):
        """
        Input validation: POST / validates request data
        Tests: Missing required fields (title, date_start, date_end, semester_id)
        """
        headers = {"Authorization": f"Bearer {admin_token}"}


        # Invalid payload missing required fields
        invalid_payload = {"description": "Missing title, dates, semester_id"}
        response = api_client.post(
            "/api/v1/sessions/",
            json=invalid_payload,
            headers=headers
        )

        # Should return 422 Unprocessable Entity for validation errors
        assert response.status_code in [400, 401, 403, 404, 422], (
            f"POST / should validate input: {response.status_code}"
        )
        


    # ── POST /sessions/book/{session_id} ────────────────────────────

    def test_book_session_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: POST /sessions/book/{session_id}
        Source: app/api/web_routes/sessions.py:book_session
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.post("/sessions/book/{session_id}", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"POST /sessions/book/{session_id} failed: {response.status_code} "
            f"{response.text}"
        )

    def test_book_session_auth_required(self, api_client: TestClient):
        """
        Auth validation: POST /sessions/book/{session_id} requires authentication
        """
        
        response = api_client.post("/sessions/book/{session_id}", json={})
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"POST /sessions/book/{session_id} should require auth: {response.status_code}"
        )

    def test_book_session_input_validation(self, api_client: TestClient, admin_token: str):
        """
        Input validation: POST /sessions/book/{session_id} validates request data
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        # Invalid payload (empty or malformed)
        invalid_payload = {"invalid_field": "invalid_value"}
        response = api_client.post(
            "/sessions/book/{session_id}",
            json=invalid_payload,
            headers=headers
        )

        # Should return 422 Unprocessable Entity for validation errors
        assert response.status_code in [400, 401, 403, 404, 422], (
            f"POST /sessions/book/{session_id} should validate input: {response.status_code}"
        )
        


    # ── POST /sessions/cancel/{session_id} ────────────────────────────

    def test_cancel_booking_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: POST /sessions/cancel/{session_id}
        Source: app/api/web_routes/sessions.py:cancel_booking
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.post("/sessions/cancel/{session_id}", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"POST /sessions/cancel/{session_id} failed: {response.status_code} "
            f"{response.text}"
        )

    def test_cancel_booking_auth_required(self, api_client: TestClient):
        """
        Auth validation: POST /sessions/cancel/{session_id} requires authentication
        """
        
        response = api_client.post("/sessions/cancel/{session_id}", json={})
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"POST /sessions/cancel/{session_id} should require auth: {response.status_code}"
        )

    def test_cancel_booking_input_validation(self, api_client: TestClient, admin_token: str):
        """
        Input validation: POST /sessions/cancel/{session_id} validates request data
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        # Invalid payload (empty or malformed)
        invalid_payload = {"invalid_field": "invalid_value"}
        response = api_client.post(
            "/sessions/cancel/{session_id}",
            json=invalid_payload,
            headers=headers
        )

        # Should return 422 Unprocessable Entity for validation errors
        assert response.status_code in [400, 401, 403, 404, 422], (
            f"POST /sessions/cancel/{session_id} should validate input: {response.status_code}"
        )
        


    # ── POST /{session_id}/check-in ────────────────────────────

    def test_check_in_to_session_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: POST /{session_id}/check-in
        Source: app/api/api_v1/endpoints/sessions/checkin.py:check_in_to_session
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.post("/{session_id}/check-in", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"POST /{session_id}/check-in failed: {response.status_code} "
            f"{response.text}"
        )

    def test_check_in_to_session_auth_required(self, api_client: TestClient):
        """
        Auth validation: POST /{session_id}/check-in requires authentication
        """
        
        response = api_client.post("/{session_id}/check-in", json={})
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"POST /{session_id}/check-in should require auth: {response.status_code}"
        )

    def test_check_in_to_session_input_validation(self, api_client: TestClient, admin_token: str):
        """
        Input validation: POST /{session_id}/check-in validates request data
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        # Invalid payload (empty or malformed)
        invalid_payload = {"invalid_field": "invalid_value"}
        response = api_client.post(
            "/{session_id}/check-in",
            json=invalid_payload,
            headers=headers
        )

        # Should return 422 Unprocessable Entity for validation errors
        assert response.status_code in [400, 401, 403, 404, 422], (
            f"POST /{session_id}/check-in should validate input: {response.status_code}"
        )

    # ── POST /{session_id}/segments ──────────────────────

    def test_create_session_segment_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: POST /{session_id}/segments
        Source: app/api/api_v1/endpoints/sessions/segments.py:create_session_segment
        """
        headers = {"Authorization": f"Bearer {admin_token}"}
        payload = {
            "label": "Smoke Test Drill",
            "position": 0,
            "duration_minutes": 15,
        }

        response = api_client.post("/{session_id}/segments", json=payload, headers=headers)

        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"POST /{{session_id}}/segments failed: {response.status_code} {response.text}"
        )

    def test_create_session_segment_auth_required(self, api_client: TestClient):
        """
        Auth validation: POST /{session_id}/segments requires authentication
        """
        payload = {"label": "No Auth Drill", "position": 0}

        response = api_client.post("/{session_id}/segments", json=payload)

        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"POST /{{session_id}}/segments should require auth: {response.status_code}"
        )

    def test_create_session_segment_input_validation(self, api_client: TestClient, admin_token: str):
        """
        Input validation: POST /{session_id}/segments rejects invalid payloads
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        # Empty label must be rejected
        response = api_client.post(
            "/{session_id}/segments",
            json={"label": "", "position": 0},
            headers=headers,
        )
        assert response.status_code in [400, 401, 403, 404, 422], (
            f"Empty label should be rejected: {response.status_code}"
        )

    def test_create_session_segment_negative_skill_target_rejected(
        self, api_client: TestClient, admin_token: str
    ):
        """
        Input validation: skill_targets with value <= 0 must be rejected (422)
        """
        headers = {"Authorization": f"Bearer {admin_token}"}
        payload = {
            "label": "Bad Skill Drill",
            "position": 0,
            "skill_targets": {"passing": -1.0},
        }

        response = api_client.post("/{session_id}/segments", json=payload, headers=headers)

        assert response.status_code in [400, 401, 403, 404, 422], (
            f"Negative skill_target weight should be rejected: {response.status_code}"
        )


