"""
Auto-generated smoke tests for admin domain
Generated by tools/generate_api_tests.py

⚠️  DO NOT EDIT MANUALLY - Regenerate using:
    python tools/generate_api_tests.py --scan-api app/api --output tests/integration/api_smoke/
"""

import pytest
from fastapi.testclient import TestClient


class TestAdminSmoke:
    """Smoke tests for admin API endpoints"""


    # ── GET /admin/analytics ────────────────────────────

    def test_admin_analytics_page_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /admin/analytics
        Source: app/api/web_routes/admin.py:admin_analytics_page
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/admin/analytics", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"GET /admin/analytics failed: {response.status_code} "
            f"{response.text}"
        )

    def test_admin_analytics_page_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /admin/analytics requires authentication
        """
        
        response = api_client.get("/admin/analytics")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"GET /admin/analytics should require auth: {response.status_code}"
        )

    def test_admin_coupons_page_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /admin/coupons
        Source: app/api/web_routes/admin.py:admin_coupons_page
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/admin/coupons", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"GET /admin/coupons failed: {response.status_code} "
            f"{response.text}"
        )

    def test_admin_coupons_page_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /admin/coupons requires authentication
        """
        
        response = api_client.get("/admin/coupons")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"GET /admin/coupons should require auth: {response.status_code}"
        )

    def test_admin_enrollments_page_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /admin/enrollments
        Source: app/api/web_routes/admin.py:admin_enrollments_page
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/admin/enrollments", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"GET /admin/enrollments failed: {response.status_code} "
            f"{response.text}"
        )

    def test_admin_enrollments_page_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /admin/enrollments requires authentication
        """
        
        response = api_client.get("/admin/enrollments")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"GET /admin/enrollments should require auth: {response.status_code}"
        )

    def test_admin_invitation_codes_page_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /admin/invitation-codes
        Source: app/api/web_routes/admin.py:admin_invitation_codes_page
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/admin/invitation-codes", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"GET /admin/invitation-codes failed: {response.status_code} "
            f"{response.text}"
        )

    def test_admin_invitation_codes_page_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /admin/invitation-codes requires authentication
        """
        
        response = api_client.get("/admin/invitation-codes")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"GET /admin/invitation-codes should require auth: {response.status_code}"
        )

    def test_admin_payments_page_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /admin/payments
        Source: app/api/web_routes/admin.py:admin_payments_page
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/admin/payments", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"GET /admin/payments failed: {response.status_code} "
            f"{response.text}"
        )

    def test_admin_payments_page_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /admin/payments requires authentication
        """
        
        response = api_client.get("/admin/payments")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"GET /admin/payments should require auth: {response.status_code}"
        )

    def test_admin_semesters_page_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /admin/semesters
        Source: app/api/web_routes/admin.py:admin_semesters_page
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/admin/semesters", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"GET /admin/semesters failed: {response.status_code} "
            f"{response.text}"
        )

    def test_admin_semesters_page_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /admin/semesters requires authentication
        """
        
        response = api_client.get("/admin/semesters")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"GET /admin/semesters should require auth: {response.status_code}"
        )

    def test_motivation_assessment_page_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /admin/students/{student_id}/motivation/{specialization}
        Source: app/api/web_routes/admin.py:motivation_assessment_page
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/admin/students/{student_id}/motivation/{specialization}", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"GET /admin/students/{student_id}/motivation/{specialization} failed: {response.status_code} "
            f"{response.text}"
        )

    def test_motivation_assessment_page_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /admin/students/{student_id}/motivation/{specialization} requires authentication
        """
        
        response = api_client.get("/admin/students/{student_id}/motivation/{specialization}")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"GET /admin/students/{student_id}/motivation/{specialization} should require auth: {response.status_code}"
        )

    def test_admin_users_page_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /admin/users
        Source: app/api/web_routes/admin.py:admin_users_page
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/admin/users", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"GET /admin/users failed: {response.status_code} "
            f"{response.text}"
        )

    def test_admin_users_page_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /admin/users requires authentication
        """
        
        response = api_client.get("/admin/users")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"GET /admin/users should require auth: {response.status_code}"
        )

    def test_instructor_enrollments_page_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /instructor/enrollments
        Source: app/api/web_routes/admin.py:instructor_enrollments_page
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/instructor/enrollments", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"GET /instructor/enrollments failed: {response.status_code} "
            f"{response.text}"
        )

    def test_instructor_enrollments_page_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /instructor/enrollments requires authentication
        """
        
        response = api_client.get("/instructor/enrollments")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"GET /instructor/enrollments should require auth: {response.status_code}"
        )

    def test_instructor_edit_student_skills_page_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /instructor/students/{student_id}/skills/{license_id}
        Source: app/api/web_routes/admin.py:instructor_edit_student_skills_page
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/instructor/students/{student_id}/skills/{license_id}", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"GET /instructor/students/{student_id}/skills/{license_id} failed: {response.status_code} "
            f"{response.text}"
        )

    def test_instructor_edit_student_skills_page_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /instructor/students/{student_id}/skills/{license_id} requires authentication
        """
        
        response = api_client.get("/instructor/students/{student_id}/skills/{license_id}")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"GET /instructor/students/{student_id}/skills/{license_id} should require auth: {response.status_code}"
        )

    def test_get_admin_dashboard_stats_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /stats
        Source: app/api/api_v1/endpoints/admin.py:get_admin_dashboard_stats
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/stats", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"GET /stats failed: {response.status_code} "
            f"{response.text}"
        )

    def test_get_admin_dashboard_stats_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /stats requires authentication
        """
        
        response = api_client.get("/stats")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"GET /stats should require auth: {response.status_code}"
        )

    def test_motivation_assessment_submit_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: POST /admin/students/{student_id}/motivation/{specialization}
        Source: app/api/web_routes/admin.py:motivation_assessment_submit
        """
        headers = {"Authorization": f"Bearer {admin_token}"}


        response = api_client.post("/admin/students/{student_id}/motivation/{specialization}", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"POST /admin/students/{student_id}/motivation/{specialization} failed: {response.status_code} "
            f"{response.text}"
        )

    def test_motivation_assessment_submit_auth_required(self, api_client: TestClient):
        """
        Auth validation: POST /admin/students/{student_id}/motivation/{specialization} requires authentication
        """
        
        response = api_client.post("/admin/students/{student_id}/motivation/{specialization}", json={})
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"POST /admin/students/{student_id}/motivation/{specialization} should require auth: {response.status_code}"
        )

    def test_motivation_assessment_submit_input_validation(self, api_client: TestClient, admin_token: str):
        """
        Input validation: POST /admin/students/{student_id}/motivation/{specialization} validates request data
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        # Invalid payload (empty or malformed)
        invalid_payload = {"invalid_field": "invalid_value"}
        response = api_client.post(
            "/admin/students/{student_id}/motivation/{specialization}",
            json=invalid_payload,
            headers=headers
        )

        # Should return 422 Unprocessable Entity for validation errors
        assert response.status_code in [400, 401, 403, 404, 422], (
            f"POST /admin/students/{student_id}/motivation/{specialization} should validate input: {response.status_code}"
        )
        


    # ── POST /instructor/students/{student_id}/skills/{license_id} ────────────────────────────

    def test_instructor_update_student_skills_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: POST /instructor/students/{student_id}/skills/{license_id}
        Source: app/api/web_routes/admin.py:instructor_update_student_skills
        """
        headers = {"Authorization": f"Bearer {admin_token}"}


        response = api_client.post("/instructor/students/{student_id}/skills/{license_id}", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 202, 204, 400, 401, 403, 404, 405, 409, 422], (
            f"POST /instructor/students/{student_id}/skills/{license_id} failed: {response.status_code} "
            f"{response.text}"
        )

    def test_instructor_update_student_skills_auth_required(self, api_client: TestClient):
        """
        Auth validation: POST /instructor/students/{student_id}/skills/{license_id} requires authentication
        """
        
        response = api_client.post("/instructor/students/{student_id}/skills/{license_id}", json={})
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [200, 400, 401, 403, 404, 405, 422], (
            f"POST /instructor/students/{student_id}/skills/{license_id} should require auth: {response.status_code}"
        )

    def test_instructor_update_student_skills_input_validation(self, api_client: TestClient, admin_token: str):
        """
        Input validation: POST /instructor/students/{student_id}/skills/{license_id} validates request data
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        # Invalid payload (empty or malformed)
        invalid_payload = {"invalid_field": "invalid_value"}
        response = api_client.post(
            "/instructor/students/{student_id}/skills/{license_id}",
            json=invalid_payload,
            headers=headers
        )

        # Should return 422 Unprocessable Entity for validation errors
        assert response.status_code in [400, 401, 403, 404, 422], (
            f"POST /instructor/students/{student_id}/skills/{license_id} should validate input: {response.status_code}"
        )
        



class TestBatchCreatePlayersSmoke:
    """
    Smoke tests for POST /admin/batch-create-players

    Coverage target: app/api/api_v1/endpoints/admin_players.py
    Covers: auth guard, instructor 403, input validation (422),
            and the happy-path (201) with a minimal valid payload.
    """

    _URL = "/api/v1/admin/batch-create-players"  # bypass _PrefixedClient prefix

    def test_batch_create_auth_required(self, api_client):
        """POST without auth → 401 or 403."""
        response = api_client.post(
            self._URL,
            json={"players": [{"email": "x@example.com", "password": "secret123", "name": "X"}]},
        )
        assert response.status_code in [401, 403], (
            f"No-auth batch-create: unexpected {response.status_code}"
        )

    def test_batch_create_instructor_forbidden(self, api_client, instructor_token: str):
        """Instructor POST → 403 (Admin only)."""
        headers = {"Authorization": f"Bearer {instructor_token}"}
        response = api_client.post(
            self._URL,
            headers=headers,
            json={"players": [{"email": "x@example.com", "password": "secret123", "name": "X"}]},
        )
        assert response.status_code in [401, 403], (
            f"Instructor batch-create should be 403: got {response.status_code}"
        )

    def test_batch_create_empty_list_validation(self, api_client, admin_token: str):
        """Admin POST with empty players list → 422 (min_length=1)."""
        headers = {"Authorization": f"Bearer {admin_token}"}
        response = api_client.post(
            self._URL,
            headers=headers,
            json={"players": []},
        )
        assert response.status_code == 422, (
            f"Empty players list should be 422: got {response.status_code}"
        )

    def test_batch_create_invalid_email_validation(self, api_client, admin_token: str):
        """Admin POST with bad email → 422 (field_validator)."""
        headers = {"Authorization": f"Bearer {admin_token}"}
        response = api_client.post(
            self._URL,
            headers=headers,
            json={"players": [{"email": "not-an-email", "password": "secret123", "name": "X"}]},
        )
        assert response.status_code == 422, (
            f"Invalid email should be 422: got {response.status_code}"
        )

    def test_batch_create_short_password_validation(self, api_client, admin_token: str):
        """Admin POST with password < 6 chars → 422."""
        headers = {"Authorization": f"Bearer {admin_token}"}
        response = api_client.post(
            self._URL,
            headers=headers,
            json={"players": [{"email": "ok@example.com", "password": "abc", "name": "X"}]},
        )
        assert response.status_code == 422, (
            f"Short password should be 422: got {response.status_code}"
        )

    def test_batch_create_admin_minimal_payload(self, api_client, admin_token: str):
        """Admin POST with 1 unique player → 201 created or 409 if already exists."""
        import uuid
        unique_email = f"smoke-batch-{uuid.uuid4().hex[:8]}@test.example.com"
        headers = {"Authorization": f"Bearer {admin_token}"}
        response = api_client.post(
            self._URL,
            headers=headers,
            json={
                "players": [{
                    "email": unique_email,
                    "password": "secret123",
                    "name": "Smoke Player",
                    "date_of_birth": "2000-01-01",
                }],
                "skip_existing": True,
            },
        )
        assert response.status_code in [200, 201, 409], (
            f"Admin batch-create (1 player): unexpected {response.status_code}"
        )

    def test_batch_create_skip_existing_idempotent(self, api_client, admin_token: str):
        """Sending the same email twice with skip_existing=True → success (no conflict)."""
        import uuid
        unique_email = f"smoke-idem-{uuid.uuid4().hex[:8]}@test.example.com"
        headers = {"Authorization": f"Bearer {admin_token}"}
        payload = {
            "players": [{
                "email": unique_email,
                "password": "secret123",
                "name": "Idem Player",
                "date_of_birth": "2000-01-01",
            }],
            "skip_existing": True,
        }
        r1 = api_client.post(self._URL, headers=headers, json=payload)
        r2 = api_client.post(self._URL, headers=headers, json=payload)
        assert r1.status_code in [200, 201], f"First call: {r1.status_code}"
        assert r2.status_code in [200, 201], f"Second call (idempotent): {r2.status_code}"
